// This runner is auto-generated by Brittle

await runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await test.load(import.meta.resolve('./parser.js'))
  await test.load(import.meta.resolve('./spec.js'))
  await test.load(import.meta.resolve('./json.js'))
  await test.load(import.meta.resolve('./cli.js'))

  test.resume()
}
