name: Publish
on:
  push:
    tags:
      - v*
permissions:
  id-token: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
    name: Publish
    steps:
      - uses: holepunchto/actions/node-base@584fd19994f94736b1afcb6adccb5156a18355a7
      - uses: holepunchto/actions/publish@584fd19994f94736b1afcb6adccb5156a18355a7
